### ISSUE TITLE
Batch size of images and masks must be the same

### ISSUE THREAD

**Issue by silent37** [lquesada/ComfyUI-Inpaint-CropAndStitch#10]
Hello, I have a question. When I manually select the face of a person by applying a mask on the image, the "CropAndStitch" node works normally. However, when I add "CLIPSeg" to automatically select the face of a person, "CropAndStitch" prompts the problem shown in the picture. What is going on? How can I solve this problem?
![微信截图_20240531124117](https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch/assets/160561218/16d47d5d-e925-4edd-9024-f9e0d599fcc9)

**Comment by lquesada** [comment]
hi!

It seems the CLIP mode is outputting masks in a different format than produced by the load image node, or even several masks at once (batch).

try passing the mask to a "convert mask to image" node, then to a preview image node and check if it's one or several masks.

If it's one, try passing the mask to the "convert mask to image" node, then to a "image to mask" node (not "convert image to mask"), pick intensity. That should yield a mask that works with inpaintcrop.

This is a workaround but it should work. Let me know!

**Comment by silent37** [comment]
Thanks for your answer. I have tested it and it works fine according to your method. But I am confused by one thing. I compared the mask preview of CLIPSeg with that of ImageToMask. The mask shape and size generated by the two are exactly the same. Why can't the former work properly?
![111111](https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch/assets/160561218/9db658f1-d0af-4a4f-96e2-b056842ac849)

**Comment by magicbot42** [comment]
I have this same issue, but I actually was hoping that it would work with multiple masks. 

I'm using grounding dino to find a bunch of things in the image, then if I separate them out with a segstomask batch and try to feed in a batch of mask it will take in a single image as input, but then i see it iterate through the mask batch but i only end up with one of the changes in the resulting image. 

Is there any trick to get it to work and retain the result of all the masks in the mask batch?

**Comment by lquesada** [comment]
Hi!

That use case will not be supported in these node, because it would break (batch image,batch mask) processing where each image is related to a mask, which is needed for animation.

I can think of several workarounds for that use case but none of them is good. :/

**Comment by magicbot42** [comment]
Any tip you have on a workarounds to try, would love to investigate that.   I don't need clean, just looking for something that works to do that.

**Comment by lquesada** [comment]
I mean, you could somehow turn the image into a batch with the same image repeated as many times as masks you have, then blend the results in, one at a time, using each of the masks. I don't know though if there are nodes already that would allow you to do this.

**Comment by lquesada** [comment]
hey :) I just pushed an update to this node.

If you pass one image and several masks, the node now works.
