### ISSUE TITLE
Add support for non-square SDXL resolutions

### ISSUE THREAD

**Issue by dt126** [lquesada/ComfyUI-Inpaint-CropAndStitch#11]
Would it be very difficult to add the ability to add Len X Width dimensions to your crop node? For example, instead of cropping to 1024 X 1024, allow DIM's to be input in the "free" mode or select specific common SDXL training resolutions such as 1344 X 768 or 896 X 1152 (that more closely match the aspect ratio of the inpaint area)? This would help with several of the SDXL models.

Also, I wanted to mention that your nodes are very helpful, but I have had the best results combining them with Comfyui Fooocus Inpaint nodes and VAE Encode & Inpaint Conditioning node. Try them if you haven't already, the combination with your inpaint Crop and Stitch nodes with these is almost perfect. It allows essentially any model (inpaint or non-inpaint) and at essentially any DN strength and your nodes crop and stitch everything back together very well.

**Comment by lquesada** [comment]
hi! I was thinking of this but it is quite complex. The main complexity (which also impacts the current "forced size" mode) is that if the mask doesn't fit in the aspect ratio without expanding past the image borders, the size won't be respected.

I have identified a workaround that would work perfectly, but implementing it is probably as much work as reimplementing the whole node and I don't have the time right now - basically, enlarge as much as possible within the image and then virtually extend the image and mask to fit the desired aspect ratio, in practice sampling a chunk that will be discarded.

I may work on this at some point, but there's some other node idea I want to play with first that would be way cooler than this.

I'll leave this issue open until I eventually fix this, but no promise on the timeline :)

Yes, I've tried that node combination and the results are great, indeed. In the example workflows I went for the most basic setup as I don't intend this repository to become a full tutorial on inpainting, just contribute these two nodes to any other inpainting workflow :)

Thank you!

**Comment by lquesada** [comment]
hey, I couldn't help thinking about this and I'm close to having that solution implemented. I'll keep you posted soon :)

**Comment by lquesada** [comment]
Currently testing.

**Comment by lquesada** [comment]
This was just committed, I'll triple check now that it doesn't break other setups. You'll likely have to recreate the node or tweak the configuration in it.

What you want to use is forced size, and set force_width and force_height to the values you want. Let me know if that works now!

**Comment by dt126** [comment]
It's working very well. Thank you so much for doing this so quickly!

I set up a workflow to use your model along with the Fooocus Inpainting. Two options your nodes with and without Fooocus added along with some sharpening as in option.
 
[Inpaint SD SDXL - Auto Mask Scaling.json](https://github.com/user-attachments/files/15523031/Inpaint.SD.SDXL.-.Auto.Mask.Scaling.json)

**Comment by lquesada** [comment]
wow that's really cool :) thanks for sharing. I'm trying it and will integrate some chunks of it in my inpainting workflow. thanks a lot!!
