### ISSUE TITLE
Add support for upscaled inpainted_image

### ISSUE THREAD

**Issue by Steudio** [lquesada/ComfyUI-Inpaint-CropAndStitch#12]
Hello,
Will it be possible to update the “Inpaint Stitch” node to accept inpainted images at a different resolution (but same proportions)?
Use case example:
I have this outpainting workflow, where the original image is quite large, so I use the “Inpaint Crop” node to crop and downsize the image to an acceptable SDXL resolution (and that works beautifully).
The inpainted image is then upscaled to increase details and to approach the original image resolution.

Unfortunately, the stitch node doesn’t accept an upscaled inpainted image.
Thanks,

**Comment by lquesada** [comment]
If the original image is 4096x4096 and you crop out 2048x2048 but force size to 1024x1024, then it is first cropped at 2048x2048, then downscaled to 1024x1024, then (your sampler), then upscaled back to 2048x2048, then stitched back in the right spot for 4096x4096.

But yeah, you can't upscale the inpainted image yourself e.g. to continue sampling.

The node won't accept images with a different resolution, but I'm actually actively working on designing a better solution to this problem. Stay tuned :)

**Comment by Steudio** [comment]
The new update broke the cropping as it is now cropping the mask
![image](https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch/assets/159500950/1179b09d-2eac-4317-bd25-226468aacd8e)
it should be cropping like this
![image](https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch/assets/159500950/b38688fd-2215-4b34-9be6-97da0093eb7a)

**Comment by lquesada** [comment]
Thanks. That was a consequence of yesterday's changes that I didn't consider. This is now fixed for "forced size". Working on "ranged size", which should be easier. Thank you!

**Comment by lquesada** [comment]
oops not pushed yet :) will do in a few :)

**Comment by Steudio** [comment]
result is different but not correct. 
![image](https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch/assets/159500950/b2e1c72f-53a6-499c-8f23-82e236811176)

**Comment by lquesada** [comment]
Hmm have you updated the node as of today? This should be working now

**Comment by Steudio** [comment]
My bad, it is good now.
I had the latest update, but my math was wrong, the outpainted image was not square so the node was doing something unexpected to compensate my math error. I guess the older node was cropping the mask on the side to make it square, but I didn't notice.

**Comment by lquesada** [comment]
Indeed, it was doing that and you could see one line of pixels at the top, but still this led me to an improvement: it now tries to fit the most of the image before bleeding out. Thank you for reporting it! Enjoy the nodes!

**Comment by lquesada** [comment]
hey, I have a question :) do you have a custom node that shows the resolution for every image in the workflow? or are you using show resolution nodes and hiding them behind the other nodes?

Thanks!

**Comment by Steudio** [comment]
I wish I could do my own nodes! I’m using [Crystools](https://github.com/crystian/ComfyUI-Crystools) get resolution node and partially hiding it behind :)
Looking forward to see your approach on different resolution inpaint images.
