### ISSUE TITLE
Broken Inpaint Stitch node if using mode: forced size

### ISSUE THREAD

**Issue by Steudio** [lquesada/ComfyUI-Inpaint-CropAndStitch#14]
The image doesn't stitch properly if using Mode: forced size
![image](https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch/assets/159500950/24ae8880-45d3-4015-ae42-cb72e0badcf9)

**Comment by lquesada** [comment]
oops fixed :) try now :)
