### ISSUE TITLE
"blur_radius_pixels" no longer available.

### ISSUE THREAD

**Issue by JakeSSRN** [lquesada/ComfyUI-Inpaint-CropAndStitch#2]
Compositing / stitching quality is now very poor. Are there plans to restore it or are we expected to use other nodes as a replacement?

**Comment by lquesada** [comment]
Hi,

Blur didn't really work the way it should. You'll get way better results of
you pipe the mask through VAE encode for inpainting and set grow mask by 12
in that node.

Cheers!

**Comment by Fexcron** [comment]
If you use VAE Encode (for inpainting) blur may not work. But the disadvantage of this method is that it only works on 1.00 denoise.

But if you used not full regeneration but only corrected some parts, you used Set Latent Noise Mask node, with which blur worked well. 

Set Latent Noise Mask allows you to correct parts of the image without the need for a complete redraw. And it is this node that is more often used for inpaint in comfyui as far as I know. Please bring back the blur.

**Comment by lquesada** [comment]
got it, that makes sense. I'll check if I can make it work better and I'll reintegrate soon :) later today, maybe.

**Comment by lquesada** [comment]
and... it doesn't quite work how I expected, it'd be really confusing for people doing vae encode for inpainting.

I'd suggest to try https://github.com/kijai/ComfyUI-KJNodes/, in particular the GrowMaskWithBlur is the exact same logic that I used for blurring. You should plumb it between the cropped mask and set latent noise mask node.

Please give it a go and let me know.

**Comment by JakeSSRN** [comment]
I've substituted in "feather mask" and it seems to be working well. It's a bit tedious to adjust though.

**Comment by lquesada** [comment]
hey Jake :) blur mask is now back (it does a mix of grow and blur), and blend is a new option that makes the stitching more seamless. You'll have to recreate the nodes.
