### ISSUE TITLE
Feature request: Add color matching function to stitch node

### ISSUE THREAD

**Issue by davidchenhs** [lquesada/ComfyUI-Inpaint-CropAndStitch#21]
Hello my friends
The function added last time still couldn't solve the problem of color difference. I solved the problem in this way.
This is definitely a feature worth updating, trust me
![image](https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch/assets/164337292/4a207138-9997-41f0-94cf-07b50aa6edda)

**Comment by lquesada** [comment]
Hi, 

I don't really understand what's going on in the screenshot, not sure what you inpainted, what's the 249 node for, and what's the difference between using it or not. 

I also don't understand why there's a grid in the output. 

If you could clarify all of this, I'll consider integrating that feature as optional in stitch.

Thanks!

**Comment by davidchenhs** [comment]
![image](https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch/assets/164337292/4e7bcf18-9aac-4eb0-b21a-f1e1bde7a735)
I tried to repair the wrong mask area, but the color of the repaired area changed. Using pixel blending or mask blur cannot completely solve this problem.
So I added the color matching node 249. The function of this node is to match the color of the repaired image with the color of the image before repair.
I tried it again today. This method is only effective under certain circumstances. Small adjustments are very effective, but the scope of application is not particularly wide.
You can refer to it, because processing the transition on the edge of the mask is not the best solution, especially when the color changes greatly after redrawing, the processed area will still stand out.

**Comment by lquesada** [comment]
this remains out of the scope of these nodes, as it doesn't work in every single case. i'll close this. thanks!
