### ISSUE TITLE
Bug in the Extend Image for Outpainting node

### ISSUE THREAD

**Issue by xuzifeung** [lquesada/ComfyUI-Inpaint-CropAndStitch#22]
I have found a bug in the Extend Image for Outpainting node. When both vertical and horizontal extensions are applied simultaneously, meaning when expanduppixels/expanddownpixels/expandleftpixels/expandrightpixels are all non-zero, or when expandupfactor/expanddownfactor/expandleftfactor/expandrightfactor are all greater than 1, the masks generated by the Inpaint Crop node will have issues. Specifically, it will turn the entire image into a non-masked area (turn white), as shown in the image below. 
![example](https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch/assets/45728405/e37aacaf-157f-4c78-a77e-a0ce7ce4f7cb)

**Comment by xuzifeung** [comment]
The cause of the problem may be that the boundary conditions are not handled correctly when expanding the image, resulting in problems with the generated mask. Specifically, when expanding an image horizontally and vertically at the same time, the expanded area may exceed the original image boundary, so the boundary needs to be handled correctly when generating the mask.

**Comment by lquesada** [comment]
Mmm disable fill mask holes in the crop node

**Comment by xuzifeung** [comment]
it works, thank you.

**Comment by xuzifeung** [comment]
it works, thank you.
