### ISSUE TITLE
Error occurred when executing InpaintCrop:  Batch size of images and masks must be the same

### ISSUE THREAD

**Issue by kawaii2020** [lquesada/ComfyUI-Inpaint-CropAndStitch#24]
![image](https://github.com/user-attachments/assets/03c61818-5b6c-43fe-8b3d-e63d012693e5)

Error occurred when executing InpaintCrop:

Batch size of images and masks must be the same

File "C:\Users\CHENG\AppData\Roaming\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\CHENG\AppData\Roaming\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\CHENG\AppData\Roaming\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\CHENG\AppData\Roaming\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inpaint-CropAndStitch\inpaint_cropandstitch.py", line 172, in inpaint_crop
assert image.shape[0] == mask.shape[0], "Batch size of images and masks must be the same"
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by lquesada** [comment]
Hi,

Clipseg is returning more than one mask for the same image, hence the nodes don't work

**Comment by kawaii2020** [comment]
![image](https://github.com/user-attachments/assets/ac357ff9-41f6-42aa-9abe-50e59bf09020)

![image](https://github.com/user-attachments/assets/16f8a7c7-b218-45af-bf40-e3fa2eb9d6aa)


But after usage of combine node ,still the same error.

**Comment by lquesada** [comment]
I think some of those nodes are outputting more than one mask each. It doesn't matter if you combine them, as it seems some of them are returning batches of more than one mask and the combine nodes aren't combining them into a single mask, but keeping the batches.

This is not an issue related to the inpaint crop and stitch nodes, I suggest you find another combination of nodes to fold clipseg output into a single mask (but I am not aware of a way to do it :))

**Comment by kawaii2020** [comment]
ok, I understand now. thank you.

**Comment by 88z** [comment]
you can just convert mask to image and then convert it back mask, it will combine masks. Just tried this, its working perfect.
