### ISSUE TITLE
Separate resize algo for mask and separate for pic

### ISSUE THREAD

**Issue by 3blackbar** [lquesada/ComfyUI-Inpaint-CropAndStitch#26]
Hey, new xinsir inpaint model expect clean black mask with no blurry edges, so i had to force nearest at al times in non free size modes when i wanted to use non nearest algo for pic

                samples = one_mask
                samples = samples.unsqueeze(1)
                samples = rescale(samples, width, height, nearest)
                samples = samples.squeeze(1)
                one_mask = samples

                if one_context_mask is not None:
                    samples = one_context_mask
                    samples = samples.unsqueeze(1)
                    samples = rescale(samples, width, height, nearest)
                    samples = samples.squeeze(1)
                    one_context_mask = samples

Can you add option to use different algo for pic and for mask? also add lanczos please

**Comment by lquesada** [comment]
Hi,

I switched masks to nearest in any case, given the node provides blurring options and I don't want to push another breaking change in the UI (if I add a new field, everyone using the nodes will have to recreate them or tweak their config).

I just submitted that change.

Thanks!
