### ISSUE TITLE
how to effectively use this to replace the background, for example, I only want to keep the original person's face

### ISSUE THREAD

**Issue by mikebilly** [lquesada/ComfyUI-Inpaint-CropAndStitch#28]

**Comment by lquesada** [comment]
mask only the face (the part you want to keep).

Then in the crop node, set "invert_mask" to true to keep the face, and set "fill_mask_holes" to false, so the face is not covered.

By the way, this is to report issues, not to provide technical support. I cannot provide technical support to users, so this is the last time I'll reply to a non-issue from you. Sorry.
