### ISSUE TITLE
Feature Request: include crop dimensions and scaling in Inpaint Crop node output

### ISSUE THREAD

**Issue by axelblaze88** [lquesada/ComfyUI-Inpaint-CropAndStitch#30]
Hello, just discovered these nodes and think they're awesome. I just think there’s one thing missing that I need. I'm working on a real world image that I previously stylized with SDXL using ControlNet. To improve the accuracy of some details that didn’t turn out quite right, I want to do inpainting with a second pass of ControlNet. I need to apply ControlNet to my real image, so I would need to crop it exactly with the dimensions and scaling of the cropped_image returned by the Inpaint Crop node.

Would it be possible to include the dimensions w/h, scaling factor, and the x/y position of the cropped region as an output of the node so I can apply the same crop to my original image or something? Or is this already implemented somehow? I’ve been messing with the nodes but can't figure out how I could do this with the current implementation... Maybe I'm missing something, still a newbie at ComfyUI 😅

**Comment by lquesada** [comment]
I have an idea for a crazy workaround :))

Use two crop nodes:
- one takes the image to inpaint and the mask. This crops the image to inpaint.
- the second crop node takes the real image BUT the same mask as above. This will crop the real image to the exact same dimensions.

You can feed that second cropped image in the controlnet, and then inpaint on the first one.

What do you think?

**Comment by axelblaze88** [comment]
Yes, that worked flawlessly, thanks a lot!
