### ISSUE TITLE
[Feature Request]: Kwai-Kolors Support

### ISSUE THREAD

**Issue by Vigilence** [lquesada/ComfyUI-Inpaint-CropAndStitch#34]
https://github.com/Kwai-Kolors/Kolors

**Comment by lquesada** [comment]
there's nothing I have to do to add support to new models, just use them in the sampler.

**Comment by Vigilence** [comment]
I tried this before making this request, atm kolors is not working with this node.  It does work with in painting in the detailed node of the inspire/impact packs.

If your tests turned out different please let me know!

**Comment by lquesada** [comment]
you probably did something wrong, as these nodes output images and masks - I'd suggest you to read kolors documentation and check that you're meeting the requirements (image size, specs, etc). Sorry, I do not have time to test these nodes with all other existing nodes, models, or hardware combinations.

Alternatively, you could also provide example screenshots of workflows (e.g. a workflow using kolors that works for you and a workflow using kolors and these nodes that doesn't work for you) and the error, and I could look through them.

**Comment by Vigilence** [comment]
Hello!

Like I said earlier, kolors inpaint works fine in segs detailer with the impact pack.  If I use the same settings with this node then it results in a bad inpaint.

The workflow with your node is the one resulting in a bad image, the workflow with the segs detailer results in a flawless inpaint.  I switched to flux in this workflow image, but I used it with kolors and its 100% great.

Maybe its the settings I am using for your node, but the same settings with flux result in a great image.

Workflow with your node that produces bad results:
![Screenshot 2024-08-30 132438](https://github.com/user-attachments/assets/b6d4b28c-5cae-4d1c-b7a7-98ed89089f0c)
![Screenshot 2024-08-30 132145](https://github.com/user-attachments/assets/43cebe06-b09c-4def-a833-b98d050ffd99)
![Screenshot 2024-08-30 132156](https://github.com/user-attachments/assets/8254c377-dd73-4054-9305-8f89e939ecdc)
![Screenshot 2024-08-30 132204](https://github.com/user-attachments/assets/ad1596ee-749d-4fdd-9e7b-2901e18a5fb0)
![Screenshot 2024-08-30 132135](https://github.com/user-attachments/assets/e1d317b7-eb12-499d-9038-0733e195b144)

Impact Segs detailer that produces flawless results:
![Screenshot 2024-08-30 132510](https://github.com/user-attachments/assets/209813d4-d4d8-4373-95ea-e8cbad961f75)

**Comment by lquesada** [comment]
sorry, but I do not understand what is the issue. Is it the quality of the sampling? I do not see the flawless results to compare.

However, different models work better at different resolutions, different models are better for inpainting than others, and my nodes work slightly different to other nodes. Maybe you're hitting a combination of different behavior of nodes that makes the model inpaint look worse.

There's nothing that I can do to adapt that to work better with Kolors though. In the end... my nodes just crop and then stitch the image back - so to Kolors that is just inpainting on an image with a mask - nothing special because of my nodes.

**Comment by Vigilence** [comment]
Yours on the left, segs detailer on the right.  Not sure why your node would produce such a pixelated inpaint compared to segs detailer.  If you can take a look at my workflow and point out any flaws or improvements for your node settings I would appreciate it!

![Screenshot 2024-08-30 141409](https://github.com/user-attachments/assets/29fb6c46-8939-4974-8b75-bb0c3594f807) ![Screenshot 2024-08-30 141431](https://github.com/user-attachments/assets/23c9adec-d4e5-490c-ad17-a0ae51ca6357)

[Kolors Inpainting1.json](https://github.com/user-attachments/files/16820831/Kolors.Inpainting1.json)

**Comment by lquesada** [comment]
Thanks for providing details!

The main difference is with my nodes you're rendering at a resolution 1024x1024 to 2048x2048, with segs detailer you're doing 1024x1024 to 1280x1280. With my nodes, that is making it as close to 2048x2048 as possible, which is probably too much.

Change min_width and min_height to 768 and max_width and max_height to 1024, or just set them all to 1024. You may also try 1280x1280 but that may still be too much. I believe trying different sizes should produce better results.

Additionally, I'd suggest to increase the context area a bit so more of the face is seen. This will provide more context to the sampler.

**Comment by Vigilence** [comment]
Hi Luis!

I tried the suggestions you provided and there was a slight improvement but the pixelation was still there.  The first image on the left is the result.  

I tried a different method to inpaint, the simple traditional method and the inpaint was much better.  I am not sure why this would be.  I included a picture of the traditional method, which is on the right.  I forgot that I actually tried this method earlier this week which is what lead me to believe that there was something that was wrong with the crop and stitch node or its settings.

The new result, with your suggestion is on the left, the traditional simple inpaint method is on the right.  The ksampler settings, mask, and prompt are the same.  

![Screenshot 2024-08-30 150152](https://github.com/user-attachments/assets/51f7ca7d-df95-40bc-889d-f0ef26e8989d)![Screenshot 2024-08-30 150201](https://github.com/user-attachments/assets/8321f841-ef84-45ee-a3f4-9ccc07975acd)

![Screenshot 2024-08-30 150043](https://github.com/user-attachments/assets/cfbafb46-ce0d-46d9-a7bc-fd17100e6f6a)

**Comment by Vigilence** [comment]
Hi Luis!

I tried the suggestions you provided and there was a slight improvement but the pixelation was still there.  After some further testing I found the issue for the pixelation, it was the rescale algorithim which was set to nearest on the inpaint crop node.  Once I switched to bislerp the pixelation is removed.  

I noticed that perhaps the segs detailer does something under the hood when it comes to inpainting and the way it treats the model.  I am not using it for segs or bbox, (dummy nodes are used for bbox and the segs is just the same mask used for crop and stitch), its only used for inpainting.  

I noticed that the segs will create a quality inpaint even at higher denoise while this node will deteriorate badly.  My guess is that the detailer node has something that deals with the kolors model better and avoids deformations where as the crop and stitch node is just a basic inpaint.

At 1.0 denoise, same ksampler settings etc. Crop and stitch top, detailer node bottom:

![Screenshot 2024-08-30 154938](https://github.com/user-attachments/assets/27c0334d-15d5-41e5-9296-a2384209f978)
![Screenshot 2024-08-30 154946](https://github.com/user-attachments/assets/f31c5286-1a10-4e62-b3bf-bf7f57c18823)





Thanks again for the help.  😊

**Comment by lquesada** [comment]
I see. Then the only other difference is the scheduler setup you're using for the sampler. I'd suggest to try other samplers in your crop-stitch setup, e.g. euler sampler with sgm_uniform scheduler instead of dpmpp_2m_sde_gpu with karras.

It seems the model is having trouble converging to something reasonable, which may be that Kolors (and I don't really know about that model) requires a different sampler.

Try euler sampler with sgm_uniform scheduler and try other combinations, maybe?
