### ISSUE TITLE
How " inpaint " and preserve the area " inpainted "

### ISSUE THREAD

**Issue by BenDes21** [lquesada/ComfyUI-Inpaint-CropAndStitch#36]
Hi there, trying to use a1111 + adetailer + inpaint for automatically detect a part of the body of my model ( let's said the arms ) and handwrite a specific text on it ( tattoo style ). The issue is that adetailer not support soft inpainting so the area ( skin ) change a lot if I want that my text appear. I already try some comfyUI workflows but Im a bit noob for make them work. Would like to know if its possible with the nodes of this pack. thanks

**Comment by lquesada** [comment]
sorry, this is not an issue with the nodes but technical support, which I cannot provide.
