### ISSUE TITLE
Preservation of inpainted area?

### ISSUE THREAD

**Issue by metamountain** [lquesada/ComfyUI-Inpaint-CropAndStitch#4]
How can i weaken the inpaint by using a noise factor so the original is preserved more? So normally there is a denoise factor for inpainting...

**Comment by lquesada** [comment]
Hi,

Instead of VAE encode for impainting, use a standard "VAE encode" node,
then pass the latent through a "set latent noise mask" noise, and then you
can set denoise in the sampler as you wish.

**Comment by metamountain** [comment]
What worked best for me was the inpaintmodel conditioning node !!! Thanks for your great support !!!!

**Comment by lquesada** [comment]
Great!

**Comment by metamountain** [comment]
![grafik](https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch/assets/129164666/971460ae-35c0-4164-846a-6f34c906adf8)

**Comment by metamountain** [comment]
Added a latent blend. To be able to control latent noise.... Now its quite fine....

**Comment by lquesada** [comment]
Thanks!! That's useful! :)
