### ISSUE TITLE
Can we have a flux workflow example?

### ISSUE THREAD

**Issue by scaruslooner** [lquesada/ComfyUI-Inpaint-CropAndStitch#40]
I tried this and got pretty result:
![image](https://github.com/user-attachments/assets/69d8142b-ee93-4e97-8551-e95dc5aa1a5c)

Also im not sure if suppose to be linking this up and using this with but it would be cool to have a workflow that incorporates:
https://huggingface.co/alimama-creative/FLUX.1-dev-Controlnet-Inpainting-Beta

**Comment by lquesada** [comment]
I'll give it a go and will reply here!

**Comment by alenknight** [comment]
i'd be curious about this too
