### ISSUE TITLE
When the Mask is near the edges, the extended mask usually produce unwanted result, Can User disable that manually?

### ISSUE THREAD

**Issue by LiJT** [lquesada/ComfyUI-Inpaint-CropAndStitch#41]
Hi Devs! 
Please check my workflow here. I listed two different method for this inpainting case
[Explain Problem for CropAndStitch.json](https://github.com/user-attachments/files/17628554/Explain.Problem.for.CropAndStitch.json)

WF overview
![show3](https://github.com/user-attachments/assets/dab25245-8684-45af-b9a1-33f1b47efeaf)

![Show1](https://github.com/user-attachments/assets/e22f2423-46bb-4efc-a7c3-de3974993f42)
![mask1](https://github.com/user-attachments/assets/68da0815-d37d-4614-9a77-95b53d30c271)
Check these two image shows, CropAndStitch forced to created a mask that extended the image somehow, I really really woult not like to do outpiant here!

![mask2](https://github.com/user-attachments/assets/cf6d752c-2d8c-4598-9059-798e697f9319)
![show2](https://github.com/user-attachments/assets/ddbe4589-a958-4c8d-b394-ea7e70c64737)
As you can see, the CropAndStitch method image is so wierd, because it is trying to make the "unseen" mirrored part of image coherent!!!

The end result looks terrible when my mask is near the edge, I know, I know, I know I can shrink the "Context expand factor", so inpaint area is much smaller. But then the inpaint model cannot look at the whole picture to make more coherent inpaint.

I really really like this node a lot. It is so elegant and require few node to run. Layerstyle on the other hand is very versatile and powerful. But, this method would not allow me to Shrink image size! Like Inpaint Crop does! So it is usually not ideal, plus Layerstyle node is huge

All in all. I just want User be able to toggle between the following mask by ourselves. I really really dont need to outpaint that extra stuff and ruining my image
![image](https://github.com/user-attachments/assets/949450be-a502-46fd-983b-aad89d8a27ce)

I hope you can catch me. Thank you so much for making this awesome node

**Comment by lquesada** [comment]
hi! one of the features of the crop and stitch nodes is that it allows overflowing out of the image with the purpose of ensuring that the target size is perfectly met. this of course has side effects in some particular setups.

Unfortunately you can't get the best of the two worlds :)

You could easily mitigate the issue by plugging in a second mask (optional_context_mask) to the crop node and drawing a bit more at the left than your mask. This will pull the context area towards the left.

**Comment by LiJT** [comment]
> hi! one of the features of the crop and stitch nodes is that it allows overflowing out of the image with the purpose of ensuring that the target size is perfectly met. this of course has side effects in some particular setups.
> 
> Unfortunately you can't get the best of the two worlds :)
> 
> You could easily mitigate the issue by plugging in a second mask (optional_context_mask) to the crop node and drawing a bit more at the left than your mask. This will pull the context area towards the left.

Thank for the fast response!

I just wish there is function that allow us just make the Mask perfectly stuck along the edge of image? like the image shown here?. Because as we know, Flux AliMama controlNet is trained for that, It will create way better generation.
Like the left one image below. 
![image](https://github.com/user-attachments/assets/5495328c-0795-40c3-8df8-1d310170c447)
I am creating a fully automatic workflow for inpainting and outpainting, currently stuck at this issue. I know user can draw the addition mask but it is not that elegant dont you think?

Thank you once again, its just a feature suggestion. Please consider it!!!

**Comment by lquesada** [comment]
yeah... as said, while this would work for some use cases, it would break the flow of other use cases. The main point of the nodes is that they keep resolution a constant and they resize (upscale, downscale) before inpainting.

If I were to change the behavior, it would work for many other use cases (mostly manual inpainting) and lots of the semantics in the node (e.g. keeping the resolution).

**Comment by evanscho** [comment]
That makes a lot of sense. Given the different use case, would it make sense to create a new node, something like Inpaint Crop With Fixed Borders, or Inpaint Crop For AliMama? I do admire that you've been minimalistic with node bloat so far, but I'm in the same boat as LiJT and do think this is a common case.
