### ISSUE TITLE
Doesn't work with FLux?

### ISSUE THREAD

**Issue by BlinkerHigh** [lquesada/ComfyUI-Inpaint-CropAndStitch#43]
Used your workflow with Shakker-Labs_FLUX.1-dev-ControlNet-Union-Pro-fp8, and the results are underwhelming.
The masked area is either unchanged (at 1 denoise) or it just won't fit the rest of the image.
https://huggingface.co/dim/Shakker-Labs_FLUX.1-dev-ControlNet-Union-Pro-fp8.safetensors/tree/main

You didn't explain why the positive prompt has 2 entries and what they do.

**Comment by lquesada** [comment]
Try another model, the one in the provided example is definitely not
underwhelming.

The two boxes are clip and t5, t5 is meant to be more detailed, this is
standard FLUX stuff that I'm not an expert on, sorry about that
