### ISSUE TITLE
[Feature Request: Add Inpainting Functionality to Extend Image Inwards

### ISSUE THREAD

**Issue by xdtxkbf** [lquesada/ComfyUI-Inpaint-CropAndStitch#44]
Hi, I’d like to request an enhancement for the "Extend Image for Outpainting" feature. Currently, it supports extending the image outward, but it would be great if there could be an option to extend the image inwards as well. This would be especially useful for scenarios where the image content needs to be adjusted or filled from the center rather than expanding the edges.

Could this functionality be added in a future update? Thanks for your consideration!

**Comment by lquesada** [comment]
visual* example please!

**Comment by lquesada** [comment]
oh I see :) this is quite messy to add to this node given the node also
does mirroring around the borders and I'd need to add every single case of
shrink height grow width etc. etc.. There are a few other "crop" nodes in
e.g. JPS-Nodes, KJNodes, essentials that allow cropping an image. Please
check those!

**Comment by lquesada** [comment]
hey! I just updated the node. The new crop node has an "extend for outpainting" feature and I made it so you can define lower than 1 factors to crop the image.
