### ISSUE TITLE
Inpaint Crop node bypass missing mask

### ISSUE THREAD

**Issue by btaens** [lquesada/ComfyUI-Inpaint-CropAndStitch#47]
If I bypass the "Inpaint Crop" node, the "image" input successfully gets bypassed to the "cropped_image" output.
However, "mask" seems to not be bypassed to "cropped_mask", as the node after it complains: Required input is missing: mask
It seems to bypass it to the "optional_context_mask", as when I connect to that input and bypass it, it works as I would expect when connecting to "mask":

Intuitively it seems though it really should connect to the "mask" input.

**Comment by lquesada** [comment]
You are right, but unfortunately ComfyUI doesn't let me define how the node bypasses :(
