### ISSUE TITLE
Mask does not get cropped

### ISSUE THREAD

**Issue by noembryo** [lquesada/ComfyUI-Inpaint-CropAndStitch#5]
This might be my fault, because when I create the mask with the MaskEditor the node works as expected.

My problem is when I try to use Crop&Stitch within the workflow that I currently use and its the one from the [ComfyUI-Photoshop](https://github.com/NimaNzrii/comfyui-photoshop) plugin (an excellent plugin BTW).
This workflow is heavily using the [cg-use-everywhere](https://github.com/chrisgoringe/cg-use-everywhere) nodes.
I don't know if this is the reason, but whatever I try, I can't get it to work properly.
What I get is this:
![mask1](https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch/assets/24675403/5b681382-43b3-4fa3-98cf-44210ff557ec)
(the mask Reroute is there to mute this input, but even without it the behavior is the same)

Whatever setting I use, I can't make it to crop the mask as it should.
What mask gets in, the same gets out.
The mask comes from Photoshop.
I tried to convert it in different ways, but nothing works.

So, maybe it's not the node's fault, I just ask here, since you know the code, you might get an idea for what is causing this, because I give up.. 😩
Thanks for your nice nodes though.. 😃👍

**Comment by lquesada** [comment]
From this information and the screenshot, I can't really debug it. I cannot
see what's connected with what. I'd suggest to try one of the example
workflows in github, check that it works, make sure you know how it
works/how it should be used, and then slowly adapt your workflow (checking
every single step).

**Comment by noembryo** [comment]
>I'd suggest to try one of the example
workflows in github, check that it works, make sure you know how it
works/how it should be used, and then slowly adapt your workflow (checking
every single step).

Yes, this is what I think I did... 😃 

All the examples are using the load image node as Image/mask input.
I checked the nodes using the MaskEditor and it worked as I expected.
It cropped the area around the mask (same area for the image crop also), applied the inpainting and then stitched the back together.
As it should.
I had the mask previews to see all the stages.

But when I tried the same in the workflow I use, the crop node did not crop the mask.
In the screenshot, the image and the mask comes from Photoshop.
All the other nodes use them normally.
I use the same image/mask combo for inpaiting and outpanting in the same workflow.
What the left preview shows is the mask that comes from Photoshop.
The same mask goes to the crop node's input.
The image has the same size.
The right mask preview shows what comes out of the crop node.
Here I expected some cropping to take place, but nothing happens.

I know that it's impossible to debug something from a screenshot, but I post it for a vague reference.
The only way to debug this is using the Photoshop plugin and it's workflow.
But as I said, I post it here because I have no other idea about a solution and maybe you could think of something.. 😉

**Comment by lquesada** [comment]
So, from the logic, if it's not cropping, it's because the mask is not
completely zeroed out.

It will crop around areas who aren't zeroes (i e. Completely black).

From your description, it's likely that the black part of the mask is not
fully pitch black.

**Comment by noembryo** [comment]
> It will crop around areas who aren't zeroes (i e. Completely black).

Aha! OK.
This is something I can use.
I seem to remember about a node that made the mask black and white only.
I'll try to find it and report here for future reference..

**Comment by noembryo** [comment]
Wait, wait,
The 0.01 works!! 🥳 
Thank you!
It is solved.. 🙏

**Comment by tazztone** [comment]
ooof i came across this issue too. it just wouldn't crop! maddening. 
so this did the trick: "remove_isolated_pixels" from the essentials node pack.
<img width="412" height="265" alt="Image" src="https://github.com/user-attachments/assets/83569b75-253f-4c49-822a-c37e141643d5" />

i redid the mask 2 times so i doubt i did a mistake there.
