### ISSUE TITLE
Question: can this work with Flux fill?

### ISSUE THREAD

**Issue by BlinkerHigh** [lquesada/ComfyUI-Inpaint-CropAndStitch#52]
If yes, any chance you could share a workflow?

**Comment by BlinkerHigh** [comment]
I tried replacing flux dev with flux fill and I just get noise as a result.

**Comment by lquesada** [comment]
I have no idea what flux fill is :)) could you share example workflows?

**Comment by dx777** [comment]
@lquesada that is new official model from flux:
https://huggingface.co/black-forest-labs/FLUX.1-Fill-dev

You can find example workflow here (in the png):
https://comfyanonymous.github.io/ComfyUI_examples/flux/#fill-inpainting-model

**Comment by lquesada** [comment]
Thanks. In principle, when the workflow is properly connected, it should work. Inpaint Crop and Stitch only alter the image and mask before sampling, so any nodes between them aren't even aware that Inpaint Crop and Stitch nodes are in the workflow.

Please give it a go!
