### ISSUE TITLE
Where can I obtain the fluxDevQ5KMGGUFQuantizationA_v10. gguf model ?

### ISSUE THREAD

**Issue by zslefour** [lquesada/ComfyUI-Inpaint-CropAndStitch#54]
Where can I obtain the fluxDevQ5KMGGUFQuantizationA_v10.gguf model ?

**Comment by lquesada** [comment]
per README.md: https://civitai.com/models/711483/flux-dev-q5km-gguf-quantization-a-nice-balance-of-speed-and-quality-in-under-9-gigabytes?modelVersionId=795785

**Comment by zslefour** [comment]
> per README.md: https://civitai.com/models/711483/flux-dev-q5km-gguf-quantization-a-nice-balance-of-speed-and-quality-in-under-9-gigabytes?modelVersionId=795785

Thank you, I also found the model download link in your workflow.
