### ISSUE TITLE
flux fill

### ISSUE THREAD

**Issue by rafstahelin** [lquesada/ComfyUI-Inpaint-CropAndStitch#56]
[flux fill.json](https://github.com/user-attachments/files/18234228/flux.fill.json)

hello i am testing crop and stitch with Flux Fill model, but getting some issue getting proper quality from it. I wonder if it has somehting to do with the  rescale algorythm, although no testing seems to be doing much in that area.

I am using a subject lora training in flux dev1 which works quite well generally with the other flux controlnet tools

**Comment by lquesada** [comment]
hi. these nodes just crop an image. if you've connected everything correctly, they should have no influence at all on how flux fill inpaints that image.

**Comment by rafstahelin** [comment]
> hi. these nodes just crop an image. if you've connected everything correctly, they should have no influence at all on how flux fill inpaints that image.

Thanks
