### ISSUE TITLE
Add support for non binary masks

### ISSUE THREAD

**Issue by nkampel** [lquesada/ComfyUI-Inpaint-CropAndStitch#8]
Thank you for your nodes; they've been incredibly effective. They can enhance the details, espeacially in low-resolution images.

Recently, I experimented with modifying the crop mask by incorporating blur to enable "diferential diffusion". The inpainting process on the cropped image yielded good results. However, upon attempting to seamlessly stitch the crop back in, I noticed a distinct border along the edges of the original binary mask. It would be fantastic to introduce support for non-binary masks and include a Gaussian blur slider in both of the nodes. 

Such an addition would greatly enhance the functionality.!

**Mask Smooth Region** and **Mask Gaussian Region** from **WAS Node suit** work well for me, as they are more performant than similar Node packs.

Thanks!

**Comment by lquesada** [comment]
hi!

The node works with non-binary masks... and it will do a perfect blend per mask.

Just blur the mask before inputting it to the crop node!

**Comment by lquesada** [comment]
The crop node now supports blur natively, and also blend (for stitching back) :)
